version: '2'
services:
  zookeeper:
    image: hurence/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: hurence/kafka:jmx
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: sandbox
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_PORT: 7071
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
